---
dist: trusty
os: linux
language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.8
  - 2.6.5
  - 2.7.1
  - ruby-head
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
jobs:
  fast_finish: false
  exclude:
    - gemfile: gemfiles/rails_5.gemfile
      rvm: 2.4.5
    - gemfile: gemfiles/rails_6.gemfile
      rvm: 2.4.5
  allow_failures:
    - rvm: ruby-head
install:
  - gem env
  - gem list bundler
  - rm -f /home/travis/.rvm/rubies/ruby-2.*/lib/ruby/gems/2.*/specifications/default/bundler-2.*.gemspec
  - echo y | rvm @global do gem install bundler -v 1.17.3 --force --default
  - gem install bundler -v 1.17.3 --force --default
  - gem install bundler -v 1.17.3
  - gem list bundler
  - bundle --version
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
script:
  - bundle exec rake test:prepare_testapp[force]
  - bundle exec rake test:all < test_responses.txt
