---
on: [push]

name: DeclareSchema Build

jobs:
  build:
    name: DeclareSchema Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.4.5, 2.5.8, 2.6.5, 2.7.1 ]
        gemfile: [ gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile ]
        exclude:
          - { gemfile: gemfiles/rails_4.gemfile, ruby: 2.7.1 }
          - { gemfile: gemfiles/rails_5.gemfile, ruby: 2.4.5 }
          - { gemfile: gemfiles/rails_6.gemfile, ruby: 2.4.5 }
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
      - name: Checkout Branch
        id: checkout_branch
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - name: Setup Ruby
        id: setup_ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: 1.17.3
          ruby-version: ${{matrix.ruby}}
      - name: Remove Bundler 2
        id: remove_bundler_2
        if: ${{ matrix.ruby >= '2.6.5' }}
        run: |
          rm -f /opt/hostedtoolcache/Ruby/2.*/x64/lib/ruby/gems/2.*/specifications/default/bundler-2.*.gemspec
          gem install bundler:1.17.3 --force --default
          gem install bundler -v 1.17.3
      - name: Appraisals
        id: appraisals
        run: |
          bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle} --gemfile=${{ matrix.gemfile }}
          bundle exec rake test:prepare_testapp[force]
          bundle exec rake test:all < test_responses.txt
