---
on: [push]

name: DeclareSchema Build

jobs:
  build:
    name: DeclareSchema Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile: [ gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile ]
    steps:
      - name: Checkout Branch
        id: checkout_branch
        uses: actions/checkout@v2
      - name: Setup Ruby
        id: setup_ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: 1.17.3
      - name: Check Ruby Version
        run: |
          ruby --version
      - name: DeclareSchema Build
        id: declare_schema_build
        run: |
          ruby --version
          bundle install
          git config --global user.email "example@example.com"
          git config --global user.name "example"
          bundle exec rake test:prepare_testapp[force]
          bundle exec rake test:all < test_responses.txt
      - name: Appraisals
        id: appraisals
        run: |
          ruby --version
          bundle install --gemfile=${{ matrix.gemfile }}
          git config --global user.email "example@example.com"
          git config --global user.name "example"
          bundle exec rake test:prepare_testapp[force]
          bundle exec rake test:all < test_responses.txt
