---
on: [push]

name: DeclareSchema Build

jobs:
  build:
    name: DeclareSchema Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        id: checkout_branch
        uses: actions/checkout@v2
      - name: Install
        id: install
        run: |
          bundle --version
          bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
      - name: Run Tests
        id: run_tests
        run: |
          bundle exec rake test:prepare_testapp[force]
          bundle exec rake test:all < test_responses.txt

