---
on: [push]

name: DeclareSchema Build

jobs:
  build:
    name: DeclareSchema Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile: [ gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile ]
    steps:
      - name: Setup Ruby
        id: setup_ruby
        uses: actions/setup-ruby@v1
      - name: Check Ruby Version
        run: |
          ruby --version
      - name: Checkout Branch
        id: checkout_branch
        uses: actions/checkout@v2
      - name: Appraisals
        id: appraisals
      - name: Install
        id: install
        run: |
          ruby --version
          git config --global user.email "example@example.com"
          git config --global user.name "example"
          bundle exec rake test:prepare_testapp[force]
          bundle exec rake test:all < test_responses.txt
